RoR Capstone project
emmanuellmhango/budget-tracker pull request #5
Opened 2023-03-29 23:13 UTC by emmanuellmhango

### Project requirements

#### Design
- You should follow these [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), including:
  - Colors.
  - Typography: font face, size and weight.
  - Layout: composition and space between elements.

- Splash screen
  - A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.

- Sign up and log in pages
  - The user should be able to register in the app with full name, email and password (all mandatory).
  - The user can log into the app using email and password.
  - If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

- Home page (categories page)
  - When the user logs in, they are presented with the categories page.
  - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
  - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
  - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- Transactions page
  - For a given category, the list of transactions is presented, ordered by the most recent.
  - At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
  - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new category" page
  - The user fills out a form to create a new category, indicating their name and icon (both mandatory).
  - The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new transaction" page
  - The user fills out a form to create a new transaction with:
    - name (mandatory)
    - amount (mandatory)
    - categories (mandatory at least one)
  - The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
  - When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

2023-03-30 02:32 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @emmanuellmhango,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-30 02:32 UTC, omar-muhamad commented on README.md
> +
- [ ] This [Video Presentation](https://www.loom.com/share/a58a98aa1817470ea1e5395c2f380eb0) you provided suppose to highlight some interesting piece of code or something you built that you are very proud of. As mentioned in this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=you%20should%20also%20highlight%20some%20interesting%20piece%20of%20code%20or%20something%20you%20built%20that%20you%20are%20very%20proud%20of.), Please fix that and kindly add the video link here in the readme file or in the Pull Request summary.

2023-03-30 02:32 UTC, omar-muhamad commented on app/views/categories/index.html.erb
> +  </center>
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=size%20and%20weight.-,Layout%3A%20composition%20and%20space%20between%20elements.,-NOTE%3A%20In%20these), Please add the correct placement for this button at the end of the page and make it take the whole page width to match the given design.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/228707903-aafe8a83-7697-4172-a74a-47d4c3d79a20.png)  | ![image](https://user-images.githubusercontent.com/68796232/228707839-a96b0675-ee80-4788-9d04-815f2632a2ae.png)  |

2023-03-30 02:32 UTC, Omar-Muhamad commented on app/views/categories/index.html.erb
> +  <% end %>
- [ ] Kindly fix the category card elements placement and add the correct widths and margin values to match the given design.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/228708898-79b0d8d3-aa83-42a3-b79c-3d2ab8540caa.png) | ![image](https://user-images.githubusercontent.com/68796232/228708803-199739c9-671b-409f-a790-9dbd07becd45.png)  |

2023-03-30 02:32 UTC, Omar-Muhamad commented on app/views/purchases/index.html.erb
> +  <% end %>
- [ ] same here,  Kindly fix the transaction card elements placement and add the correct widths and margin values to match the given design.

| Given Design  | Your Design |
| ------------- | ------------- |
|![image](https://user-images.githubusercontent.com/68796232/228712649-2372ec27-4c80-4579-8564-432fef72933f.png) | ![image](https://user-images.githubusercontent.com/68796232/228712699-5f1fa741-f0bc-4fa9-a91e-f6450b0b9991.png) |

2023-03-30 02:32 UTC, Omar-Muhamad commented on app/views/purchases/index.html.erb
> +  </center>
- [ ] Same here, As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=size%20and%20weight.-,Layout%3A%20composition%20and%20space%20between%20elements.,-NOTE%3A%20In%20these), Please add the correct placement for this button at the end of the page and make it take the whole page width to match the given design.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/228712936-e3e144b2-6ed8-4ed0-941f-1d47b976490a.png)  | ![image](https://user-images.githubusercontent.com/68796232/228713056-bd1a212f-4d20-49a5-ac88-1726e583ae70.png) |

2023-03-31 00:09 UTC, arslanbisharat requested changes
Hi @emmanuellmhango, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- The Pull Request has a proper title and description. ✔️
- You have added a descriptive Readme file. Good Job. ✔️
- There is no linter error is present. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please make sure you right descriptive comments. Commenting involves placing Human Readable Descriptions inside of computer programs detailing what the Code is doing. Proper use of commenting can make code maintenance much easier, as well as helping make finding bugs faster. Further, commenting is very important when writing functions that other people will use. :x:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 00:09 UTC, arslanbisharat commented on app/controllers/application_controller.rb
> +  def after_sign_in_path_for(_resource)
- [ ] Upon signning up, I am getting error. Please fix this. 

![image](https://user-images.githubusercontent.com/58504655/228990858-e5650727-746f-49b7-83ae-766497964b06.png)

2023-03-31 00:09 UTC, arslanbisharat commented on app/views/categories/edit.html.erb
> +
- [ ] After signup and getting an error, If I try to again sign up I get an error of email already being used. But if I try to use the same Email and Password in Login page, it is not working. It also doesn't have any error.

2023-03-31 18:50 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @emmanuellmhango    :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 18:57 UTC, merged